#!/bin/sh

trap "pkill -P $$" SIGINT
trap "pkill -P $$" EXIT

parse() {
	awk '{print $2}' | grep -v -E '/proc|/dev|/bus|/sys|/lib' | grep -w -v /
}

while true ; do
    for m in `cat /proc/mounts | parse` ; do
        printf "[%s] " `basename $m`
    done
    echo

    if [ -e /usr/bin/inotifywait ] ; then
        /usr/bin/inotifywait /etc/mtab >/dev/null 2>&1
        sleep 0.2
    else
        sleep 20
    fi
done

