#!/bin/sh

trap "pkill -P $$" SIGINT
trap "pkill -P $$" EXIT

INOWAIT=/usr/bin/inotifywait

parse() {
	cat /proc/mounts | 
    awk '{print $2}' | 
    grep -v -E '/proc|/dev|/bus|/sys|/lib' | 
    grep -w -v /
}

while true ; do
    for m in `parse` ; do
        printf "[%s] " `basename $m`
    done
    echo

    if [ -e $INOWAIT ] ; then
        $INOWAIT /etc/mtab >/dev/null 2>&1
        sleep 0.2
    else
        sleep 20
    fi
done

