#!/bin/sh

parse() {
	awk '{print $3}' | grep -v -E '/proc|/dev|/bus|/sys|/lib' | grep -w -v /
}


supply() {
	exec tail -n0 -F "/var/log/messages" 
}

filter() {
	echo "wake"
	exec grep --line-buffered "mount"
}

process() {
	while read x ; do
		for m in `mount | parse` ; do
			printf "[%s] " `basename $m`
		done
		echo
	done
}

{ supply | filter | process ; } &
trap "pkill -P $!" EXIT
wait

