#!/bin/sh

IFS=$'\n'

which /usr/bin/wimaxcu 2>/dev/null || exit -1
which /usr/bin/wimaxll 2>/dev/null || exit -1

while true ; do
    echo
    /usr/bin/wimaxcu status connect | grep 'Name' | awk -F : '{print $2}'
    /usr/bin/wimaxll -i wmx0 wait-for-state-change >/dev/null 2>&1
    sleep 1
done

