#!/bin/sh

IFS=$'\n'
IFACE=wlan0
xpid=99999

iwgrab() {
    essid=`/sbin/iwconfig "$IFACE" | sed -n 's/.*ESSID:"\([^\"]\+\)"/\1/ p'`
    case "$essid" in
    "") echo ;;
     *) echo "ESSID: $essid" ;;
    esac
}

trap "pkill -p $$" EXIT 

iwgrab

tail -F -n0 /var/log/messages | 
grep --line-buffered -E "$IFACE" | 
while read l ; do
    { ps | grep -q "$xpid" ; } && continue
    { iwgrab ; sleep 4 ; iwgrab ; } &
    xpid=$!
done

