#!/bin/sh

IFS=$'\n'
IFACE=wlan0

iwgrab() {
    { /sbin/iwconfig $IFACE | grep ESSID || echo ; } | 
        sed 's/.*ESSID:"\([^\"]\+\)"/ESSID: \1/'
}

iwgrab

tail -F -n0 /var/log/messages | 
grep --line-buffered -E "CONNECTED|DISCONNECTED" | 
while read l ; do
    { sleep 3 ; iwgrab ; } &
done

